/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pratikum11;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Tiket extends javax.swing.JFrame {

    private int hargaTiket;
    private int jumlahTiket;
    private static int ticketNumber = 1;

    /**
     * Creates new form Tiket
     */
    public Tiket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_umur = new javax.swing.JTextField();
        txt_jumlahtiket = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        btn_cektotal = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nama             :");

        jLabel4.setText("Umur              :");

        jLabel5.setText("Jumlah Tiket :");

        jLabel6.setText("Total");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setText("Penjualan Tiket");

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        txt_jumlahtiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahtiketActionPerformed(evt);
            }
        });

        txt_total.setEditable(false);
        txt_total.setText("Rp");
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        btn_cektotal.setText("Cek Total");
        btn_cektotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cektotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_simpan))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cektotal)
                                .addGap(0, 116, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_jumlahtiket)
                                    .addComponent(txt_nama)
                                    .addComponent(txt_umur))))))
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_umur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txt_jumlahtiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_cektotal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btn_simpan)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_jumlahtiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahtiketActionPerformed
          int jumlahTiket = Integer.parseInt(txt_jumlahtiket.getText());

    // Get the age from txt_umur text field
    int umur = Integer.parseInt(txt_umur.getText());

    // Calculate the ticket price based on age
    int hargaTiket;
    if (umur < 17) {
        JOptionPane.showMessageDialog(this, "Usia harus di atas 17 tahun");
        return;
    } else if (umur >= 17 && umur <= 25) {
        hargaTiket = 50000;
    } else if (umur >= 26 && umur <= 35) {
        hargaTiket = 100000;
    } else {
        hargaTiket = 150000;
    }

    // Calculate the total price
    int total = jumlahTiket * hargaTiket;

    // Display the price and total in their respective text fields

    txt_total.setText("Rp" + Integer.toString(total));
    }//GEN-LAST:event_txt_jumlahtiketActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
 

    // Get the number of tickets
    int jumlahTiket = Integer.parseInt(txt_jumlahtiket.getText());

    // Get the age from txt_umur text field
    int umur = Integer.parseInt(txt_umur.getText());

    // Calculate the ticket price based on age
    int hargaTiket;
    if (umur < 17) {
        JOptionPane.showMessageDialog(this, "Usia harus di atas 17 tahun");
        return;
    } else if (umur >= 17 && umur <= 25) {
        hargaTiket = 50000;
    } else if (umur >= 26 && umur <= 35) {
        hargaTiket = 100000;
    } else {
        hargaTiket = 150000;
    }

    // Calculate the total price
    int total = jumlahTiket * hargaTiket ;

    // Display the price and total in their respective text fields
    txt_jumlahtiket.setText(Integer.toString(hargaTiket));
    txt_total.setText(Integer.toString(total));
    }//GEN-LAST:event_txt_totalActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
       String nama = txt_nama.getText();
    int umur = Integer.parseInt(txt_umur.getText());
    int jumlahTiket = Integer.parseInt(txt_jumlahtiket.getText());

    String totalText = txt_total.getText();
    int total = Integer.parseInt(totalText.replaceAll("\\D+", ""));

    // Validate the age
    if (umur < 17) {
        JOptionPane.showMessageDialog(this, "Usia harus di atas 17 tahun");
        return;
    }

    // Increment the ticket number
    int currentTicketNumber = ticketNumber++;

    // Display the input results in a dialog message
    String message = "Data berhasil disimpan.\n\n"
            + "Nomor Tiket      : " + currentTicketNumber + "\n"
            + "Nama             : " + nama + "\n"
            + "Umur             : " + umur + "\n"
            + "Jumlah Tiket     : " + jumlahTiket + "\n"
            + "Total Harga      : Rp " + total;
    JOptionPane.showMessageDialog(this, message);

    // Clear the form fields
    txt_nama.setText("");
    txt_umur.setText("");
    txt_jumlahtiket.setText("");
    txt_total.setText("");

           }//GEN-LAST:event_btn_simpanActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void btn_cektotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cektotalActionPerformed
 String nama = txt_nama.getText();
        int umur = Integer.parseInt(txt_umur.getText());
        int jumlahTiket = Integer.parseInt(txt_jumlahtiket.getText());

        // Validate the age
        if (umur < 17) {
            JOptionPane.showMessageDialog(this, "Usia harus di atas 17 tahun");
            return;
        }

        // Calculate the ticket price based on age
        int hargaTiket;
        if (umur >= 17 && umur <= 25) {
            hargaTiket = 50000;
        } else if (umur >= 26 && umur <= 35) {
            hargaTiket = 100000;
        } else {
            hargaTiket = 150000;
        }

        // Calculate the total price
        int total = jumlahTiket * hargaTiket;

        // Display the price and total in their respective text fields
        txt_total.setText("Rp" + Integer.toString(total));
    }//GEN-LAST:event_btn_cektotalActionPerformed
                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cektotal;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_jumlahtiket;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_umur;
    // End of variables declaration//GEN-END:variables
}
